### ISSUE TITLE
咨询框架

### ISSUE THREAD

**Issue by gege96** [jneless/EyerissF#4]
您好！
我是在校的一名学生，最近想在您的框架上做一些关于CNN accelerator在dataflow方面的改善实验，不知道您能否提供一份框架具体的readme？非常感谢！！！我的邮箱是yangxiangjie@hust.edu.cn，希望能得到您的回复

**Comment by jneless** [comment]
这个只是一个Eyeriss芯片的模拟器
框架可以理解为是对chip的一个驱动程序，可以使用虚拟的Hive完成CNN的构建
但是BP没写···不能训练，只能用一些虚拟的filter计算，或者是用其他platform训练好的filter

如果你是想用eyeriss这个chip的话，这个可能会对你有用，但是如果只是单纯的搭建CNN的话，这个就用处不大。反而建议你去用Pytorch或者Keras。

ReadME暂时没时间， https://github.com/jneless/EyerissF/blob/master/Lenet5_Hive_Auto.ipynb
和https://github.com/jneless/EyerissF/blob/master/Lenet5_Hive_Manuel_withPics.ipynb  这两个notebook已经够用了

看你的需求吧，如果有其他问题欢迎发邮件给我 jialinli@linkedin.com。
